### ISSUE TITLE
Where is the example file?

### ISSUE THREAD

**Issue by flippercy** [yihengsun/TransBoost#1]
Hi @yihengsun:

Congrats on the great paper! I'd like to test this algorithm with my internal data; where is the example file (Transboost_example.ipynb as mentioned in the readme file), please? I did not find it in any folder.

Thank you.

**Comment by yihengsun** [comment]
Hi @flippercy , 
I've uploaded `Transboost_example.ipynb` in the root directory.
Thank you for pointing that out :)
